### ISSUE TITLE
Compiling with MinGW command line

### ISSUE THREAD

**Issue by CiroboyBR** [eliasYFGM/Luna2#1]
allegro 5.0.10

cd luna/src

gcc -c main.c game.c player.c states/gamestate.c states/deadstate.c states/scarestate.c

gcc main.o game.o player.o deadstate.o gamestate.o scarestate.o -o luna -lallegro-5.0.10-mt -lallegro_primitives-5.0.10-mt -lallegro_font-5.0.10-mt -lallegro_image-5.0.10-mt -lallegro_acodec-5.0.10-mt -lallegro_audio-5.0.10-mt -lallegro-5.0.10-monolith-mt -lm

**Comment by EliMakerDash** [comment]
You have problems linking with the Allegro libs?

I think you're not supposed to link with the "monolith" library when you are _already_ linking with the other Allegro libraries (separately). Either remove _-lallegro-5.0.10-monolith-mt_ or just link with this library.

**Comment by CiroboyBR** [comment]
not problem. This commands compile and link your projetc in MinGW line-command
